[package]
name = "illustrator-rs"
version = "0.1.0"
authors = ["Hanakla <hanakla.dev@gmail.com>"]
license = "MIT"
edition = "2021"
build = "build.rs"

[build-dependencies]
bindgen = "0.71"
glob = "0.3.2"
