[package]
name = "helloworld_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
illustrator-rs = { path = "../illustrator-rs" }

[build-dependencies]
pipl = "0.1.1"
